slogan: "个人Blog && Wiki"

menu:
  - title: 归档
    url: archives
    intro: 文章归档
    icon: fa fa-archive
  - title: 分类
    url: categories
    intro: 文章分类
    icon: fa fa-folder
  - title: 标签
    url: tags
    intro: 所有标签
    icon: fa fa-tags
  - title: 关于
    url: about
    intro: 我的足迹
    icon: fa fa-user
links:
  - title: "My Github"
    url: http://www.github.com/szwchao
    intro: "My Github account."
    icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.ico
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR
